# Essential Papers Recommender - Topics Configuration
# 
# This file defines the research topics for which essential papers will be collected.
# Each topic will generate a separate GitHub issue with recommended papers.

topics:
# Configuration Notes:
# - name: Unique identifier for the topic (used in GitHub issue titles)
# - query: PubMed search query string
# - max_papers: Maximum number of papers to retrieve from PubMed
# - essential_count: Number of top papers to include in the essential list
# - enabled: Whether to process this topic (set to false to temporarily disable)

  # Machine Learning in Healthcare
  - name: "machine-learning-antibody"
    query: "machine learning AND antibody"
    max_papers: 100
    essential_count: 3
    enabled: true

  # Cancer Immunotherapy
  - name: "treg-cell"
    query: "treg AND cancer AND immunotherapy"
    max_papers: 100
    essential_count: 3
    enabled: true

 # Cancer Immunotherapy
  - name: "cancer-immunotherapy"
    query: "cancer AND immunotherapy"
    max_papers: 100
    essential_count: 3
    enabled: true

  # Artificial Intelligence Drug Discovery
  - name: "ai-drug-discovery"
    query: "artificial intelligence AND drug discovery"
    max_papers: 100
    essential_count: 3
    enabled: true  # Disabled example

  # De novo protein design
  - name: "de-novo-protein-design"
    query: "de novo design AND artificial intelligence AND protein design"
    max_papers: 100
    essential_count: 3
    enabled: true  # Disabled example

  # bioinformatics
  - name: "bioinformatics"
    query: "bioinformatics AND machine learning AND deep learning"
    max_papers: 100
    essential_count: 3
    enabled: true  # Disabled example
